services:
  - type: web
    name: hiring-agent
    env: python
    plan: starter
    buildCommand: "pip install -r requirements.txt"
    startCommand: "bash start.sh"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: OPENAI_API_KEY
        sync: false
      - key: DEFAULT_MODEL
        value: gpt-4o
      - key: ENVIRONMENT
        value: production
    healthCheckPath: /api/health
    disk:
      name: hiring-agent-disk
      mountPath: /opt/render/project/storage
      sizeGB: 1
    autoDeploy: true
    branch: main