# Weight configurations for different candidate types
weight_modes:
  professional:
    name: "Working Professionals"
    description: "Optimized for experienced candidates with work history"
    weights:
      resume_jd_match: 0.20      # 20% - Solid foundation
      github_analysis: 0.15      # 15% - Code quality matters
      linkedin_analysis: 0.15    # 15% - Professional presence
      technical_blogs: 0.10      # 10% - Thought leadership
      project_quality: 0.10      # 10% - Side projects/portfolio
      work_experience: 0.25      # 25% - Most important for professionals
      social_presence: 0.05      # 5% - Nice to have
  
  fresher:
    name: "Interns & Freshers"
    description: "Optimized for new graduates and entry-level candidates"
    weights:
      resume_jd_match: 0.25      # 25% - Foundation skills crucial
      github_analysis: 0.30      # 30% - Code portfolio very important
      linkedin_analysis: 0.05    # 5% - Less important for freshers
      technical_blogs: 0.05      # 5% - Rare for freshers
      project_quality: 0.25      # 25% - Academic/personal projects crucial
      work_experience: 0.05      # 5% - Limited experience expected
      social_presence: 0.05      # 5% - Nice to have

# Default mode selection
default_mode: "professional"

platform_weights:
  github:
    code_quality: 0.4
    project_complexity: 0.3
    contribution_consistency: 0.2
    domain_relevance: 0.1
  
  linkedin:
    technical_content: 0.5
    professional_network: 0.2
    endorsements: 0.2
    certifications: 0.1
  
  twitter:
    technical_content: 0.6
    engagement_quality: 0.3
    community_involvement: 0.1
  
  medium:
    article_quality: 0.4
    domain_expertise: 0.4
    readership_engagement: 0.2
  
  projects:
    technical_complexity: 0.3
    code_quality: 0.25
    live_deployment: 0.2
    performance: 0.15
    innovation: 0.1
  
  work_experience:
    company_tier: 0.4
    role_relevance: 0.3
    tenure: 0.2
    achievements: 0.1

scoring_thresholds:
  excellent: 85
  good: 70
  average: 55
  below_average: 40